### ISSUE TITLE
Update docs for templating regarding etlua support

### ISSUE THREAD

**Issue by JordanMajd** [Fizzadar/luapress.org#4]
Update documentation to:

- Mention support for `etlua` templating.
- Describe how to use the `--template` command argument.

I can submit a PR sometime this week.

**Comment by Fizzadar** [comment]
This should be covered by https://github.com/Fizzadar/luapress.org/commit/dda043ca4a19300ef09dad4a29c6a4ddc2021130.

Moving the site elsewhere but hoping to have this live soon.
